services:
  frontend:
    container_name: site_ishikawa_educampo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_ENABLE_TEST_FARMS=${NEXT_PUBLIC_ENABLE_TEST_FARMS:-false}
    restart: unless-stopped
    ports:
      - "3000:3000"
    # O Docker vai ler o seu ficheiro .env local e injetar no contentor
    env_file:
      - .env
    environment:
      - NODE_ENV=production # Ative ela na versão de produção.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ishikawa_network

networks:
  ishikawa_network:
    driver: bridge